RestReserv/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using RestReserv.Domain;
using RestReserv.Models.Comment;
using RestReserv.Models.Restaurant;
using RestReserv.Repository.Contracts;

namespace RestReserv.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentRepository commentRepository;
        private readonly IRestaurantRepository restaurantRepository;

        public CommentController(ICommentRepository commentRepository, IRestaurantRepository restaurantRepository)
        {
            this.commentRepository = commentRepository;
            this.restaurantRepository = restaurantRepository;
        }

        [HttpGet]
        public IActionResult AddComment(int restaurantId)
        {
            var restaurnt = restaurantRepository.GetById(restaurantId);

            ViewBag.Restaurnt = restaurnt.Adapt<RestaurantModel>();
            return View();
        }

        public async Task<IActionResult> AddComment(CommentCreateModel commentCreateModel)
        {
            var restaurnt = restaurantRepository.GetById(commentCreateModel.RestaurantId);

            var comment = new Comment
            {
                Body = commentCreateModel.Body,
                Date = DateTime.Now,
                RestaurantId = restaurnt.Id,
                User = commentCreateModel.User
            };

            await commentRepository.Create(comment);

            return RedirectToAction("Index", "Rest");

            //return View();
        }
    }
}

RestReserv/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using RestReserv.Domain;
using RestReserv.Models.Order;
using RestReserv.Models.Restaurant;
using RestReserv.Repository.Contracts;

namespace RestReserv.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly IRestaurantRepository restaurantRepository;
        private readonly ITableRepository tableRepository;

        public OrderController(IOrderRepository orderRepository, ITableRepository tableRepository, IRestaurantRepository restaurantRepository)
        {
            this.orderRepository = orderRepository;
            this.tableRepository = tableRepository;
            this.restaurantRepository = restaurantRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var orders = orderRepository.GetAll()?
                .Adapt<IEnumerable<OrderModel>>();

            ViewBag.Orders = orders;

            return View();
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                throw new Exception("Заказ не найден!");
            var model = order.Adapt<OrderModel>();
            model.Address = order.Table.Restaurant.Address;

            ViewBag.Order = model;

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var restaurants = restaurantRepository.GetAll()?
                .Select(x => new RestaurantModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    Title = x.Title,
                    City = x.City.Name
                });

            ViewBag.Restaurants = restaurants;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderCreateModel createModel)
        {
            try
            {
                var restaurant = restaurantRepository.GetAll()?.FirstOrDefault(x => x.Id == createModel.RestaurantId);
                if (restaurant == null)
                    throw new Exception("Адрес ресторана указан не верно!");
                if (string.IsNullOrWhiteSpace(createModel.UserName))
                    throw new Exception("Имя заказчика не может быть пустым");

                var table = restaurant.Tables.FirstOrDefault(x => x.CountPlace >= createModel.CountPerson
                && (x.Orders == null || !x.Orders.Any(v => v.Date == createModel.Date) || !x.Orders.Any(v=>v.Time == createModel.Time)));

                if (table == null)
                    throw new Exception("В данном заведении нет свободных мест на данное время!");

                var order = new Order
                {
                    CountPerson = createModel.CountPerson,
                    Date = createModel.Date,
                    Phone = createModel.Phone,
                    Time = createModel.Time,
                    UserName = createModel.UserName,
                    Table = table
                };

                await orderRepository.Create(order);

                return RedirectToAction("Detail", new { id = order.Id });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", ex.Message);
            }
            //return View();

        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var order = orderRepository.GetById(id);
                if (order == null)
                    throw new Exception("Заказ не найден!");

                if (order.Date <= DateTime.Now
                    && order.Time < DateTime.Now.TimeOfDay)
                    throw new Exception("Невозможно удалить данный заказ!");

                await orderRepository.Delete(order);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", ex.Message);
            }
        }

        public IActionResult Error(string error)
        {
            ViewBag.Error = error;
            return View();
        }
    }
}

RestReserv/Controllers/RestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using RestReserv.Models.Comment;
using RestReserv.Models.Restaurant;
using RestReserv.Repository.Contracts;

namespace RestReserv.Controllers
{
    public class RestController : Controller
    {
        private readonly ICityRepository cityRepository;
        private readonly IRestaurantRepository restaurantRepository;
        private readonly ICommentRepository commentRepository;

        public RestController(ICityRepository cityRepository,
                              IRestaurantRepository restaurantRepository,
                              ICommentRepository commentRepository)
        {
            this.restaurantRepository = restaurantRepository;
            this.cityRepository = cityRepository;
            this.commentRepository = commentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var restaurants = restaurantRepository.GetAll()?
                .Select(x => new RestaurantModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    Title = x.Title,
                    City = x.City.Name
                });
            var comments = commentRepository.GetAll()?.OrderByDescending(x => x.Id).Take(5).Adapt<IEnumerable<CommentModel>>();

            ViewBag.Restaurants = restaurants;
            ViewBag.Comments = comments;

            return View();
        }
    }
}

RestReserv/Views/Rest/Index.cshtml
@using RestReserv.Models.Restaurant
@using RestReserv.Models.Comment
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div class='container main_wrapper'>
        <div class='box-menu box-flex'>
            <div class='light title'><span>REST</span>AURANT</div>
            <div class='container_for_buttons'>
                <button id='reserve' class='light feedback'><a href='@Url.Action("Create","Order")'><span>RESERVE</span></a></button>
                <button class='light feedback'><a href='@Url.Action("Index","Order")'><span>SHOW ORDERS</span></a></button>
            </div>
        </div>
        <div class='all_feedbacks box-flex'>
            <div class='light title'>FEEDBACKS</div>
        </div>


        @if (ViewBag.Restaurants is IEnumerable<RestaurantModel> restaurants && restaurants.Any())
        {
            <div class='list_of_restaurants'>
                @foreach (var restaurant in restaurants)
                {
                <div class='rest box-flex'>
                    <div class='rest_img'></div>
                    <div class='rest_title'>@restaurant.Title</div>
                    <div class='rest_address'>@restaurant.City, @restaurant.Address</div>
                    <div class='rating'><a href='@Url.Action("AddComment","Comment", new { restaurantId = restaurant.Id })'><span>добавить отзыв</span></a></div>
                    <div class='rest_opening-hours'></div>
                </div>
                }
            </div>
        }
        else
        {
            <div>Упс..кажется у вас нет ресторанов :(</div>
        }
        <!-- вторая строка -->

        @if (ViewBag.Comments is IEnumerable<CommentModel> comments && comments.Any())
        {
            <div class='list_of_feedbacks style-10'>
                @foreach (var comment in comments)
                {
                    <div class='one_feedback'>
                        <div class='text_feedback'>@comment.Body</div>
                        <div class='data_user_feedback'>
                            <div class='name_user_feedback'>@comment.User</div>
                            <div class='date_feedback'>@comment.Date.ToShortDateString()</div>
                        </div>
                    </div>
                }
            </div>
        }
        else
        {
            <div>Кажется никто еще не осталвял отзывов..</div>
        }

    </div>
</body>