RestReserv/Models/Order/OrderCreateModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RestReserv.Models.Order
{
    public class OrderCreateModel
    {
        public int Id { get; set; }

        public int RestaurantId { get; set; }

        /// <summary>
        /// Дата заказа
        /// </summary>
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        /// <summary>
        /// Время заказа
        /// </summary>
        public TimeSpan Time { get; set; }
        /// <summary>
        /// Количество персон
        /// </summary>
        public int CountPerson { get; set; }
        /// <summary>
        /// Имя заказчика
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// Телефон заказчика
        /// </summary>
        public string Phone { get; set; }
    }
}

RestReserv/Models/Order/OrderModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RestReserv.Models.Order
{
    public class OrderModel
    {
        public int Id { get; set; }
        /// <summary>
        /// Дата заказа
        /// </summary>
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        /// <summary>
        /// Время заказа
        /// </summary>
        public TimeSpan Time { get; set; }
        /// <summary>
        /// Количество персон
        /// </summary>
        public int CountPerson { get; set; }
        /// <summary>
        /// Имя заказчика
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// Телефон заказчика
        /// </summary>
        public string Phone { get; set; }

        public string Address { get; set; }
    }
}

RestReserv/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using RestReserv.Domain;
using RestReserv.Models.Order;
using RestReserv.Models.Restaurant;
using RestReserv.Repository.Contracts;

namespace RestReserv.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly IRestaurantRepository restaurantRepository;
        private readonly ITableRepository tableRepository;

        public OrderController(IOrderRepository orderRepository, ITableRepository tableRepository, IRestaurantRepository restaurantRepository)
        {
            this.orderRepository = orderRepository;
            this.tableRepository = tableRepository;
            this.restaurantRepository = restaurantRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var orders = orderRepository.GetAll()?
                .Adapt<IEnumerable<OrderModel>>();

            ViewBag.Orders = orders;

            return View();
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var order = orderRepository.GetById(id);
            if (order == null)
                throw new Exception("Заказ не найден!");
            var model = order.Adapt<OrderModel>();
            model.Address = order.Table.Restaurant.Address;

            ViewBag.Order = model;

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            var restaurants = restaurantRepository.GetAll()?
                .Select(x => new RestaurantModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    Title = x.Title,
                    City = x.City.Name
                });

            ViewBag.Restaurants = restaurants;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderCreateModel createModel)
        {
            try
            {
                var restaurant = restaurantRepository.GetAll()?.FirstOrDefault(x => x.Id == createModel.RestaurantId);
                if (restaurant == null)
                    throw new Exception("Адрес ресторана указан не верно!");
                if (string.IsNullOrWhiteSpace(createModel.UserName))
                    throw new Exception("Имя заказчика не может быть пустым");

                var table = restaurant.Tables.FirstOrDefault(x => x.CountPlace >= createModel.CountPerson
                && (x.Orders == null || !x.Orders.Any(v => v.Date == createModel.Date) || !x.Orders.Any(v=>v.Time == createModel.Time)));

                if (table == null)
                    throw new Exception("В данном заведении нет свободных мест на данное время!");

                var order = new Order
                {
                    CountPerson = createModel.CountPerson,
                    Date = createModel.Date,
                    Phone = createModel.Phone,
                    Time = createModel.Time,
                    UserName = createModel.UserName,
                    Table = table
                };

                await orderRepository.Create(order);

                return RedirectToAction("Detail", new { id = order.Id });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", ex.Message);
            }
            //return View();

        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var order = orderRepository.GetById(id);
                if (order == null)
                    throw new Exception("Заказ не найден!");

                if (order.Date <= DateTime.Now
                    && order.Time < DateTime.Now.TimeOfDay)
                    throw new Exception("Невозможно удалить данный заказ!");

                await orderRepository.Delete(order);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", ex.Message);
            }
        }

        public IActionResult Error(string error)
        {
            ViewBag.Error = error;
            return View();
        }
    }
}

RestReserv/Controllers/RestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using RestReserv.Models.Comment;
using RestReserv.Models.Restaurant;
using RestReserv.Repository.Contracts;

namespace RestReserv.Controllers
{
    public class RestController : Controller
    {
        private readonly ICityRepository cityRepository;
        private readonly IRestaurantRepository restaurantRepository;
        private readonly ICommentRepository commentRepository;

        public RestController(ICityRepository cityRepository,
                              IRestaurantRepository restaurantRepository,
                              ICommentRepository commentRepository)
        {
            this.restaurantRepository = restaurantRepository;
            this.cityRepository = cityRepository;
            this.commentRepository = commentRepository;
        }

        public async Task<IActionResult> Index()
        {
            var restaurants = restaurantRepository.GetAll()?
                .Select(x => new RestaurantModel
                {
                    Id = x.Id,
                    Address = x.Address,
                    Title = x.Title,
                    City = x.City.Name
                });
            var comments = commentRepository.GetAll()?.OrderByDescending(x => x.Id).Take(5).Adapt<IEnumerable<CommentModel>>();

            ViewBag.Restaurants = restaurants;
            ViewBag.Comments = comments;

            return View();
        }
    }
}

RestReserv/Views/Order/Create.cshtml
@using RestReserv.Models.Restaurant
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div class='container'>
        <div class='div'>
            <div id='choose' class='wrapper'>
                <div class='wrapper_for_form'>
                    <form id='form' method="post">
                        <p class='title_form'>CHOOSE THE BEST TABLE</p><br>

                        <div class='field'>

                            <select id='address' name='restaurantId' area-placeholder='Address' required>
                                <option value='0'>Выберите адрес</option>
                                @if (ViewBag.Restaurants is IEnumerable<RestaurantModel> restaurants)
                                {
                                    @foreach (var restaurant in restaurants)
                                    {
                                        <option value='@restaurant.Id'>@restaurant.City,  @restaurant.Address</option>
                                    }
                                }
                                @*<option value='2'>Брест, ул.Октябрьская, 10</option>
        <option value='3'>Иваново, ул.Северная, 4</option>
        <option value='4'>Минск, ул.Немига, 5</option>
        <option value='5'>Витебск, ул.Великоморская, 54</option>
        <option value='6'>Минск, ул.Гурского, 1</option>*@
                            </select>
                        </div>

                        <div class='field'>
                            <input id="date" name='date' placeholder="Date" class="textbox-n" type="text"
                                   readonly='true' required />
                            <!--  onfocus="(this.type='date')" onblur="if(!this.value)this.type='text'" /> -->
                            <img id='calendar' class='img_input' src='~/icons/streamline-icon-calendar-1@24x24.png' />
                            <!-- <input id='date' name='date' type='date'> -->
                        </div>

                        <div class='field'>
                            <input id='time' name='time' type='text' placeholder="Time" required>
                            <img class='img_input clock' src='~/icons/streamline-icon-time-clock-circle-1@24x24.png'>
                            <select id='persons' name='countPerson' area-placeholder='persons' required>
                                <option value='default'></option>
                                <option value='1'>1</option>
                                <option value='2'>2</option>
                                <option value='3'>3</option>
                                <option value='4'>4</option>
                                <option value='5'>5</option>
                                <option value='6'>6</option>
                            </select>
                        </div>

                        <div class='field'>
                            <input id='name' name='userName' type='name' placeholder="Name">
                            <img class='img_input' src='~/icons/streamline-icon-single-neutral@24x24.png'>
                        </div>

                        <div class='field'>
                            <input id='phone' name='phone' type='phone' placeholder="Your number">
                            <img class='img_input' src='~/icons/streamline-icon-phone@24x24.png'>
                        </div>

                        <input id='form_reserve' type='submit' class='dark button_reserve' value='RESERVE'>

                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

RestReserv/Views/Order/Detail.cshtml
@using RestReserv.Models.Order
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div class='container'>
        <div class='div'>

            <div id='reservation' class='wrapper'>
                <div class='wrapper_for_viewing_result wrapper_for_form'>
                    @if (ViewBag.Order is OrderModel order)
                    {
                    <p id='title_output'>YOUR RESERVATION</p><br>
                    <p id='name_output' class=''>@order.UserName</p>
                    <p id='date_output' class=''><img src='~/icons/streamline-icon-calendar-1@32x32.png'>@order.Date</p>
                    <p id='time_output' class=''><img src='~/icons/streamline-icon-time-clock-circle-1@32x32.png'>@order.Time</p>
                    <p id='persons_output' class=''><img src='~/icons/streamline-icon-multiple-neutral-2@32x32.png'>@order.CountPerson</p>
                    <p id='address_output' class=''></p>
                    <p id='welcom'>WAITING FOR YOU!</p>
                    <button id='home' class=''>
                        <a href='@Url.Action("Index","Order")'>
                            <img src='~/icons/streamline-icon-house-chimney-1@34x34.png'></img>
                        </a>
                    </button>
                    }
                </div>

            </div>
        </div>
    </div>
</body>

RestReserv/Views/Order/Index.cshtml
@using RestReserv.Models.Order

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Orders is IEnumerable<OrderModel> orders)
{

    <body>
        <div class='container'>
            <div class='wrapper_for_table_title'>
                <h3 class='title_of_table'>TABLE OF ORDERINGS</h3>
            </div>
            <div class='wrapper_for_table style-10'>
                <div class='table'>
                    @foreach (var order in orders)
                    {
                        <div class='item one_order'>
                            <div class='order_name'><span>ИМЯ: @order.UserName</span></div>
                            <div class='order_date'><span>ДАТА: @order.Date</span></div>
                            <div class='order_time'><span>ВРЕМЯ: @order.Time</span></div>
                            <div class='order_persons'><span>КОЛИЧЕСТВО ЧЕЛОВЕК: @order.CountPerson</span></div>
                            <div class='order_phone'><span>ТЕЛЕФОН: </span></div>
                            <div class='order_address'><span>АДРЕСС РЕСТОРАНА: </span></div>
                        </div>

                        <div class='item wrapper_for_delete'>
                            <button class='order_delete'><a href='@Url.Action("Delete","Order", new { id = order.Id })'>DELETE</a></button>
                        </div>
                    }
                </div>
            </div>

            <button class='ok'><a href='@Url.Action("Index","Rest")'>OK</a></button>
        </div>
    </body>
}
else
{
    <h2>Заказов нет.</h2>
}